#!/usr/bin/env node
/**
 * Compile timeline_accel.wat → wasm, embed as base64 for single-file builds.
 */
import { readFileSync, writeFileSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { execSync } from 'child_process'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const wat = resolve(root, 'wasm/timeline_accel.wat')
const wasmOut = resolve(root, 'src/renderer/timeline_accel.wasm')
const jsOut = resolve(root, 'src/renderer/wasmBytes.js')

if (!existsSync(wat)) {
  console.error('Missing', wat)
  process.exit(1)
}

execSync(`wat2wasm "${wat}" -o "${wasmOut}"`, { stdio: 'inherit' })

const wasm = readFileSync(wasmOut)
const b64 = wasm.toString('base64')
writeFileSync(jsOut, `// Auto-generated by scripts/embed-wasm.mjs — do not edit.\nexport default '${b64}'\n`)
console.log(`Embedded timeline_accel.wasm (${wasm.length} bytes) → src/renderer/wasmBytes.js`)
